# Generated by Django 4.2.4 on 2023-08-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_url', models.URLField(max_length=255, unique=True)),
                ('playlist_uri', models.CharField(max_length=255, unique=True)),
                ('playlist_name', models.CharField(max_length=255)),
                ('playlist_likes', models.PositiveBigIntegerField()),
                ('playlist_genre', models.CharField(max_length=255)),
                ('published_by', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
