# Generated by Django 4.2.4 on 2023-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistselector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('token_type', models.CharField(max_length=255)),
                ('expires_in', models.PositiveIntegerField()),
            ],
        ),
    ]
