# Generated by Django 4.2.4 on 2023-08-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlistselector', '0002_accesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='expires_in',
            new_name='expires_at',
        ),
    ]
