# Generated by Django 4.2.4 on 2023-08-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistselector', '0003_rename_expires_in_accesstoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
